name: Sync Documentation Changes

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.js' 

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Need full history to get previous versions

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install comment-parser

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          files: |
            src/**/*.js

      - name: Get changed Changes
        id: changed-lines
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          git diff HEAD^ HEAD --unified=0 -- "src/**/*.js" | node scripts/parse-diff.js
          echo "Changed lines JSON content:"
          cat changed-lines.json
          has_doc_change=$(node -e "const data = require('./changed-lines.json'); console.log(data.hasDocumentationChange ? 'true' : 'false')")
          echo "HAS_DOCUMENTATION_CHANGE=$has_doc_change" >> $GITHUB_ENV
          
          # Create a file with only the changed lines (filtering out unnecessary entries)
          node -e "
            const fs = require('fs');
            const data = require('./changed-lines.json');
            const formattedChanges = Object.entries(data.changes)
              .map(([file, changes]) => {
                // Filter out any change objects that don't have a valid 'lines' property
                const filtered = changes.filter(change => change.lines && change.lines.trim() !== '');
                if (!filtered.length) return '';
                return filtered.map(change =>
                  '- ' + file + ' (lines ' + change.lines + ')' +
                  (change.context && change.context.length ? ' [' + change.context.map(c =>
                    'Context start: ' + c.start + (c.end ? ' | Context end: ' + c.end : '')
                  ).join('; ') + ']' : '')
                ).join('\n');
              })
              .filter(entry => entry) // Remove empty entries
              .join('\n');
            fs.writeFileSync('formatted-changes.txt', formattedChanges);
            console.log('Formatted changes written to formatted-changes.txt');
          "
          echo "Formatted changes written to formatted-changes.txt"

      - name: Get supported languages
        id: supported-languages
        run: |
          git clone https://github.com/webermayank/test-website-repo.git
          languages=$(ls -d test-website-repo/translations/*/ | sed 's|test-website-repo/translations/||g' | sed 's|/||g' | grep -v 'en' | tr '\n' ', ')
          echo "SUPPORTED_LANGUAGES=$languages" >> $GITHUB_ENV
          echo "$languages" > supported-languages.txt

      - name: Create issue in website repo
        if: github.event_name == 'push' && steps.changed-files.outputs.any_changed == 'true' && env.HAS_DOCUMENTATION_CHANGE == 'true'
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.WEBSITE_REPO_TOKEN }}
          script: |
            const fs = require('fs');
            
            // Read files instead of using environment variables to avoid escaping issues
            const changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}";
            const changedLines = fs.readFileSync('formatted-changes.txt', 'utf8');
            const supportedLanguages = fs.readFileSync('supported-languages.txt', 'utf8');
            
            await github.rest.issues.create({
              owner: "webermayank",
              repo: "test-website-repo",
              title: "Documentation Change in Main Repo - Translation Needed",
              body: `Translation needed for the following JSDoc documentation changes:\n\n${changedLines}\n\nPlease translate these changes into the supported languages: ${supportedLanguages}`
            });