name: Sync Documentation Changes

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history to ensure git diff works

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          files: |
            docs/**

      - name: Get changed lines
        id: changed-lines
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          git diff HEAD^ HEAD --unified=0 -- "docs/**" > diff.txt
          echo "Diff content:"
          cat diff.txt
          node scripts/parse-diff.js
          echo "Changed lines content:"
          cat changed-lines.txt
          # Remove newlines and set CHANGED_LINES
          changed_lines=$(cat changed-lines.txt | tr '\n' ' ')
          echo "CHANGED_LINES=$changed_lines" >> $GITHUB_ENV

      - name: Get supported languages
        id: supported-languages
        run: |
          git clone https://github.com/webermayank/test-website-repo.git
          languages=$(ls -d test-website-repo/translations/*/ | sed 's|test-website-repo/translations/||g' | sed 's|/||g' | grep -v 'en' | tr '\n' ', ')
          echo "SUPPORTED_LANGUAGES=$languages" >> $GITHUB_ENV

      - name: Create issue in website repo
        if: github.event_name == 'push' &&  steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.WEBSITE_REPO_TOKEN }}
          script: |
            const changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}";
            const changedLines = "${{ env.CHANGED_LINES }}";
            const supportedLanguages = "${{ env.SUPPORTED_LANGUAGES }}";
            await github.rest.issues.create({
              owner: "webermayank",
              repo: "test-website-repo",
              title: "Documentation Change in Main Repo - Translation Needed",
              body: `Translation needed for the following files:\n\n${changedLines}\n\nPlease translate these changes into the supported languages: ${supportedLanguages}`
            });