name: Sync Documentation Changes

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*.js'  # Target JavaScript files
  pull_request:
    branches: [main]
    paths:
      - 'src/**/*.js'

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          files: |
            src/**/*.js

      - name: Get changed lines
        id: changed-lines
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          git diff HEAD^ HEAD --unified=0 -- "src/**/*.js" | node scripts/parse-diff.js
          echo "Changed lines JSON content:"
          cat changed-lines.json
          has_doc_change=$(node -e "const data = require('./changed-lines.json'); console.log(data.hasDocumentationChange ? 'true' : 'false')")
          echo "HAS_DOCUMENTATION_CHANGE=$has_doc_change" >> $GITHUB_ENV
          changed_lines=$(node -e "
            const data = require('./changed-lines.json');
            const formattedChanges = Object.entries(data.changes).map(([file, changes]) => 
              changes.map(change => 
                '- ' + file + ' (lines ' + change.lines + ')' + 
                (change.context ? ' [' + change.context.map(c => 
                  'Start: \"' + c.start + '\" | End: \"' + c.end + '\"'
                ).join('; ') + ']' : '')
              ).join(' ')
            ).join('\n');
            console.log(formattedChanges);
          ")
          echo "Formatted changed lines: $changed_lines"
          echo "CHANGED_LINES=$changed_lines" >> $GITHUB_ENV

      - name: Get supported languages
        id: supported-languages
        run: |
          git clone https://github.com/webermayank/test-website-repo.git
          languages=$(ls -d test-website-repo/translations/*/ | sed 's|test-website-repo/translations/||g' | sed 's|/||g' | grep -v 'en' | tr '\n' ', ')
          echo "SUPPORTED_LANGUAGES=$languages" >> $GITHUB_ENV

      - name: Create issue in website repo
        if: github.event_name == 'push' && steps.changed-files.outputs.any_changed == 'true' && env.HAS_DOCUMENTATION_CHANGE == 'true'
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.WEBSITE_REPO_TOKEN }}
          script: |
            const changedFiles = "${{ steps.changed-files.outputs.all_changed_files }}";
            const changedLines = "${{ env.CHANGED_LINES }}";
            const supportedLanguages = "${{ env.SUPPORTED_LANGUAGES }}";
            await github.rest.issues.create({
              owner: "webermayank",
              repo: "test-website-repo",
              title: "Documentation Change in Main Repo - Translation Needed",
              body: `Translation needed for the following files:\n\n${changedLines}\n\nPlease translate these changes into the supported languages: ${supportedLanguages}`
            });